{{- if and .Values.gitlab.token (not .Values.gitlab.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gte.fullname" . }}
  labels:
    {{- include "gte.labels" . | nindent 4 }}
stringData:
  GITLAB_READ_TOKEN: {{ .Values.gitlab.token | quote }}
{{- end }}
